### PR TITLE
Cleanups and bug fixes

### PR DESCRIPTION
**Pull request by deltabeard**
This pull request fixes the following issues:
- https://github.com/libretro/snes9x2010/issues/89 Black screen on 6MiB Super Mario World ROM hack.
- https://github.com/libretro/snes9x2010/issues/102 Use of printf in logging

Overscan is removed within these series of changes. This is a work-around to the following overscan related issues:
- https://github.com/libretro/snes9x2010/issues/27
- https://github.com/libretro/snes9x2010/issues/45

Further work:
- All unused configuration options are removed.
- Fixed some compiler warnings.
- Removed unused code sections.
- Modified pitch calculation. Considering the width and height of the framebuffer is given, the pitch should be a function of the width. Let me know if this is incorrect.

All these items have been tested with RetroArch.

Many thanks.

### CODE REVIEW

**Comment by Tatsuya79** [comment]
What's going on in libretro_core_options.h?
It seems there was a Turkish translation coming from the other updated main core (options named snes9x_*).

Only the options named snes9x_next_* are the actual valid variables used in libretro.c.

You made the wrong ones from that Turkish part the new US v2 options which should be reverted.

**Comment by deltabeard** [comment]
I missed that. I'll also remove the unused options for the Turkish translation.
It beggars the question why it was merged in the first place though.

**Comment by deltabeard** [comment]
Fixed the config options, and tested them in RetroArch.

**Comment by deltabeard** [comment]
Thank you! Please close the four issues. :smiley:

**Pull request merged**
